spring:
  application:
    name: Personal-Server
  data:
    mongodb:
      uri: mongodb+srv://softwaredev1112_db_user:j5Ss4OSg58U05nen@personalserver.wtmczyv.mongodb.net/?appName=PersonalServer
      database: Personal-Server
      auto-index-creation: true

server:
  port: 9245

security:
  jwt:
    secret: avery-long-secret-formypersonal-server!
    access-token-expiry: 15m
    refresh-token-expiry: 30d

logging:
  level:
    root: INFO